#!/usr/bin/env python

import sys, argparse, logging, pprint, requests

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Codefresh HTTP Deploy')

    parser.add_argument('url', help="The URL of the endpoint on which a deploy webhook is listening")
    parser.add_argument('--method', action='store', dest='method', default='GET', choices=['get', 'GET', 'post', 'POST'])
    parser.add_argument('--bearertoken', action='store', dest='bearertoken')

    args = parser.parse_args()
    
    
    print '---------------------------------'
    print 'HTTP DEPLOY STARTED'
    print '---------------------------------'
    print ''
    print "* url:", args.url
    print "* method", args.method.upper()
    
    try:
        if args.method and args.method.lower() == 'post':
            call = requests.post
        else:
            call = requests.get
        
        headers = {}
        if args.bearertoken is not None:
            print "* bearertoken", args.bearertoken
            headers["Authorization"] = "Bearer " + args.bearertoken
        
        print ''
        print "Performing call..."
        
        r = call(args.url, headers=headers)
        
        print ''
        print '---------------------------------'
        print 'RESPONSE'
        print '---------------------------------'
        print 'Status', r.status_code
        print r.text

        if r.status_code < 200 or r.status_code > 299:
            print 'HTTP call failed, exiting...'
            sys.exit(2)

        sys.exit(0)
        
    except Exception as e:
        print '---------------------------------'
        print("ERROR: {}".format(e.message))
        sys.exit(1)
